title: API Knowledge
description: This is an open toolbox of API knowledge that runs on GitHub, providing a single resource to use when seeking knowledge of the API sector.
image: https://postman-toolboxes2.s3.amazonaws.com/assets/api.png
url: https://postman-toolboxes.github.io/api-knowledge
email: covid-19@postman.com

github_user: postman-toolboxes
github_repo: api-knowledge
github_branch: master

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'kin.lane@postman.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
